#!/usr/bin/env bash
# Regenerate derived files from canonical sources — run after editing rules/ or .cursorrules
#   PROMPT.md       ← AGENTS.md + rules/*.md (single-file bundle for ChatGPT/Gemini/Claude.ai web)
#   .clinerules     ← .cursorrules (identical content)
#   .windsurfrules  ← .cursorrules (identical content)
set -euo pipefail
cd "$(dirname "$0")"

RULE_FILES=$(ls rules/*.md | sort)
RULE_COUNT=$(echo "$RULE_FILES" | wc -l | tr -d ' ')

{
  echo "# gas-best-practices — Bundled prompt (single file)"
  echo ""
  echo "> All ${RULE_COUNT} rule files concatenated into one. Paste into ChatGPT custom instructions, GPT Project knowledge, or any AI that does not auto-load files."
  echo "> Source: https://github.com/kpcrmv4/gas-best-practices"
  echo "> Generated by build.sh — DO NOT EDIT BY HAND (edit rules/*.md then rerun ./build.sh)"
  echo ""
  echo "---"
  echo ""
  cat AGENTS.md
  for f in $RULE_FILES; do
    echo ""
    echo "---"
    echo ""
    cat "$f"
  done
} > PROMPT.md

cp .cursorrules .clinerules
cp .cursorrules .windsurfrules

echo "✓ PROMPT.md regenerated (${RULE_COUNT} rule files, $(wc -l < PROMPT.md | tr -d ' ') lines)"
echo "✓ .clinerules / .windsurfrules synced from .cursorrules"
